### ISSUE TITLE
reading list of CoT from Mu Li

### ISSUE THREAD

**Issue by zhaochenyang20** [Timothyxxx/Chain-of-ThoughtsPapers#1]
![image](https://user-images.githubusercontent.com/74843776/202343339-fd8ff42e-72f9-4108-9ef8-4ad8a1d03084.png)

**Comment by Timothyxxx** [comment]
I see. Never mind. They did things for people of different background. We have followers of different countries, thus we cannot post this video resource here. And I personally may not interested in conclude that into a paper. 

Thanks for noticing!
