### ISSUE TITLE
Consider adding our paper (CoT Collection)

### ISSUE THREAD

**Issue by SeungoneKim** [Timothyxxx/Chain-of-ThoughtsPapers#17]
Hello, thanks for providing this awesome repository introducing different chain-of-thought variants!
Could you consider adding our CoT Collection dataset? It's a massive instruction dataset consisted of 1.84 million rationales across 1060 NLP tasks for CoT Fine-tuning!

https://arxiv.org/abs/2305.14045

Thank you in advance!

**Comment by Timothyxxx** [comment]
Sure, thanks for your attention!
